// global variables
// Paths of all input and output files
extern char A_file_paths_train[word_count][100];
extern char A_file_paths_test[word_count][100];
extern char B_file_paths_train[word_count][100];
extern char B_file_paths_test[word_count][100];
extern char Pi_file_paths_train[word_count][100];
extern char Pi_file_paths_test[word_count][100];
extern char Observation_sequence_file_paths_train[word_count][100];
extern char Observation_sequence_file_paths_test[word_count][100];
extern char sample_files_train[word_count][TRAINING_SEQUENCES+1][100];
extern char sample_files_test[word_count][TESTING_SEQUENCES+1][100];
extern char codebook_file_path[100];

// varaibles generated by model
extern long double A[N+1][N+1];
extern long double B[N+1][M+1];
extern long double Pi[N+1];
extern long int Observation_sequence[TRAINING_SEQUENCES+1][T+1];
extern long double alpha[T+1][N+1];
extern long double beta[T+1][N+1];
extern long double delta[N+1][T+1];
extern long double psi[N+1][T+1];
extern long double P_star, old_pstar;
extern int Q_star[T+1];
extern long double xai[T+1][N+1][N+1];
extern long double gamma[T+1][N+1];
extern long double A_BAR[N+1][N+1];
extern long double B_BAR[N+1][M+1];
extern long double Pi_BAR[N+1];
extern long double collect_A[TRAINING_SEQUENCES+1][N+1][N+1];
extern long double collect_B[TRAINING_SEQUENCES+1][N+1][M+1];
extern long double codebook[M+1][p+1];
extern long double weight[p];